"""Create report images model

Revision ID: 05a7d9bb201f
Revises: 19172480821d
Create Date: 2025-11-23 23:27:38.803292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a7d9bb201f'
down_revision: Union[str, Sequence[str], None] = '19172480821d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_images_file_key'), 'report_images', ['file_key'], unique=False)
    op.create_index(op.f('ix_report_images_id'), 'report_images', ['id'], unique=True)
    op.create_index(op.f('ix_report_images_report_id'), 'report_images', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_images_report_id'), table_name='report_images')
    op.drop_index(op.f('ix_report_images_id'), table_name='report_images')
    op.drop_index(op.f('ix_report_images_file_key'), table_name='report_images')
    op.drop_table('report_images')
    # ### end Alembic commands ###
