"""Add avatar field to user model

Revision ID: 19172480821d
Revises: 1ae2564252d0
Create Date: 2025-11-23 17:59:53.042455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19172480821d'
down_revision: Union[str, Sequence[str], None] = '1ae2564252d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_has_avatar', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_has_avatar')
    # ### end Alembic commands ###
