"""Add thanks model

Revision ID: 801c4ac20bdb
Revises: c53b3a77a6b5
Create Date: 2026-01-10 16:59:17.151361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '801c4ac20bdb'
down_revision: Union[str, Sequence[str], None] = 'c53b3a77a6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thanks',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('from_user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('to_user_id', UUID(as_uuid=True), nullable=False),
    sa.Column('request_id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thanks_from_user_id'), 'thanks', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_thanks_request_id'), 'thanks', ['request_id'], unique=False)
    op.create_index(op.f('ix_thanks_to_user_id'), 'thanks', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thanks_to_user_id'), table_name='thanks')
    op.drop_index(op.f('ix_thanks_request_id'), table_name='thanks')
    op.drop_index(op.f('ix_thanks_from_user_id'), table_name='thanks')
    op.drop_table('thanks')
    # ### end Alembic commands ###
