"""Add response model

Revision ID: c53b3a77a6b5
Revises: c2490701ea09
Create Date: 2026-01-10 15:30:33.675057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'c53b3a77a6b5'
down_revision: Union[str, Sequence[str], None] = 'c2490701ea09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
        sa.Column('id', UUID(), nullable=False),
        sa.Column('request_id', UUID(), nullable=False),
        sa.Column('volunteer_id', UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_request_id'), 'responses', ['request_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_responses_request_id'), table_name='responses')
    op.drop_table('responses')
