"""create elder model

Revision ID: ef514266c542
Revises: b7c863a6595d
Create Date: 2025-11-17 01:04:11.853029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef514266c542'
down_revision: Union[str, Sequence[str], None] = 'b7c863a6595d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relative_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=False),
    sa.Column('physical_limitations', sa.String(), nullable=False),
    sa.Column('disease', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('features', sa.String(), nullable=False),
    sa.Column('hobbies', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relative_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elders_id'), 'elders', ['id'], unique=True)
    op.create_index(op.f('ix_elders_relative_id'), 'elders', ['relative_id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_elders_relative_id'), table_name='elders')
    op.drop_index(op.f('ix_elders_id'), table_name='elders')
    op.drop_table('elders')
    # ### end Alembic commands ###
